compose/config/routes.rb
Rails.application.routes.draw do
  resources :teachers
  resources :subjects
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :students
	resources :students
	#root 'students#index'
	root 'pages#info'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

compose/app/models/teacher.rb
class Teacher < ApplicationRecord
  belongs_to :subject
  	def self.search(search)
  where("imie LIKE ? OR nazwisko LIKE ?", "%#{search}%", "%#{search}%") 
end
    validates :imie, :length => { :in => 3..15, :message => "Długość minimum 3." }, :format => { :with => /\A[A-ZĄĆĘŁŃÓŚŹŻ][a-ząćęłńóśźż]+\z/, :message => "nie może zawierać liczb. Musi zaczynać się wielką literą." }
    validates :nazwisko, :length => { :in => 3..20, :message => "musi mieć długość minimum 3." }, :format => { :with => /\A[A-ZĄĆĘŁŃÓŚŹŻ][a-ząćęłńóśźż]+\z/, :message => "nie może zawierać liczb. Musi zaczynać się wielką literą." }
    validates :pesel, :length => { :is => 11, :message => "ma złą długość!" },:format => { :with => /\A[0-9][0-9]((([0][1,3,5,7,8])|([1][0,2]))(([0][1-9])|([1-2][0-9])|([3][0-1])))|((([0][4,6,9])|([1][1]))(([0][1-9])|([1-2][0-9])|([3][0])))|(([02])(([0][1-9])|([1-2][0-9])))[0-9]{5}+\z/, :message => "jest nieprawdziwy."}, :numericality => { :only_integer => true, :message => "Musi składać się z samych cyfr." }

end

compose/app/controllers/teachers_controller.rb
class TeachersController < ApplicationController
  before_action :set_teacher, only: [:show, :edit, :update, :destroy]
  # GET /teachers
  # GET /teachers.json

def index
  @teachers = Teacher.all
  if params[:search]
    @teachers = Teacher.search(params[:search]).order("created_at DESC")
  else
    @teachers = Teacher.all.order("created_at DESC")
  end
end
  # GET /teachers/1
  # GET /teachers/1.json
  def show
  end

  # GET /teachers/new
  def new
    @teacher = Teacher.new
  end

  # GET /teachers/1/edit
  def edit
  end

  # POST /teachers
  # POST /teachers.json
  def create
    @teacher = Teacher.new(teacher_params)

    respond_to do |format|
      if @teacher.save
        format.html { redirect_to @teacher, notice: 'Pomyślnie dodano przedmiot.' }
        format.json { render :show, status: :created, location: @teacher }
      else
        format.html { render :new }
        format.json { render json: @teacher.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /teachers/1
  # PATCH/PUT /teachers/1.json
  def update
    respond_to do |format|
      if @teacher.update(teacher_params)
        format.html { redirect_to @teacher, notice: 'Pomyślnie zaktualizowano przedmiot.' }
        format.json { render :show, status: :ok, location: @teacher }
      else
        format.html { render :edit }
        format.json { render json: @teacher.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /teachers/1
  # DELETE /teachers/1.json
  def destroy
    @teacher.destroy
    respond_to do |format|
      format.html { redirect_to teachers_url, notice: 'Pomyślnie usunięto przedmiot.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_teacher
      @teacher = Teacher.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def teacher_params
      params.require(:teacher).permit(:imie, :nazwisko, :pesel, :subject_id)
    end

end

compose/app/helpers/teachers_helper.rb
module TeachersHelper
end

compose/app/views/teachers/_form.html.erb
<%= form_with(model: teacher, local: true) do |form| %>
  <% if teacher.errors.any? %>
    <div id="error_explanation">
      <h5 style="color:red;"><%= "Błąd." %> Nie udało się zapisać tego ucznia:</h5>

      <ul>
      <% teacher.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<div class="container">
  <div class="btn-group form-inline">
    <%= form.label :imie , :class => "btn btn-warning btn-sm"%>
    <%= form.text_field :imie %>
  </div>

  <div class="btn-group form-inline">
    <%= form.label :nazwisko , :class => "btn btn-warning btn-sm"%>
    <%= form.text_field :nazwisko %>
  </div>

  <div class="btn-group form-inline">
    <%= form.label :pesel , :class => "btn btn-warning btn-sm"%>
    <%= form.text_field :pesel %>
  </div>

  <div class="btn-group form-inline">
    <%= form.label :subject_id, :class => "btn btn-warning btn-sm"%>
    <%= form.collection_select :subject_id, Subject.all, :id, :nazwa, {}, { class: "form-control" } %>
  </div>

<p>
  <div class="actions form-inline">
    <%= form.submit 'Zapisz', :class => "btn btn-dark btn-sm"%>
  </div>
</p>

</div>
<% end %>

compose/app/views/teachers/edit.html.erb
<div class="container">
<br>
<h2><p>Edycja nauczycieli</p></h2>
<hr />
<%= render 'form', teacher: @teacher %>
</br>

<center>
	<%= link_to 'Wyświetl', @teacher , :class => "btn btn-dark btn-sm"%> |
	<%= link_to 'Wróć', teachers_path , :class => "btn btn-dark btn-sm"%>
</center>
</div>

compose/app/views/teachers/index.html.erb
<p id="notice"><%= notice %></p>
<center><h1>Lista nauczycieli</h1></center>
<div class="container">


<%= form_tag(teachers_path, method: :get , id: "search-form") do %>
    <%= text_field_tag :search, params[:search], placeholder: "Znajdź nauczyciela" %>
    <%= submit_tag "Szukaj", name: nil, class: "btn btn-warning btn-sm" %>
<% end %>

<% if @teachers.blank? %>
  <h4>Nie istnieje nauczyciel '<%= params[:search] %>'.</h4>
<% end %>


<center><%= link_to 'Dodaj nowego nauczyciela', new_teacher_path, :class => "btn btn-warning btn-sm" %></center>
</br>
<table class="table table-stripped table-hover">

  <thead>
    <tr>
      <th>Imię</th>
      <th>Nazwisko</th>
      <th>Pesel</th>
      <th>Przedmiot</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @teachers.each do |teacher| %>
      <tr>
        <td><%= teacher.imie %></td>
        <td><%= teacher.nazwisko %></td>
        <td><%= teacher.pesel %></td>
        <td><%= teacher.subject.nazwa %></td>
        <td><%= link_to 'Wyświetl', teacher, :class => "btn btn-dark btn-sm" %></td>
        <td><%= link_to 'Edytuj', edit_teacher_path(teacher) , :class => "btn btn-warning btn-sm" %></td>
        
       <!--<td><%= link_to 'Usuń', teacher, method: :delete, data: { confirm: 'Czy na pewno chcesz usunąć?' }, :class => "btn btn-dark btn-sm"  %></td>-->
         <td><%= link_to 'Usuń', teachers_path , :class => "btn btn-dark btn-sm"%></td>
    <% end %>
  </tbody>
</table>
     <%= link_to 'Anuluj szukanie', teachers_path , :class => "btn btn-dark btn-sm"%>

</div>
<br>

compose/app/views/teachers/new.html.erb
<div class="container">
<h1>Nowy nauczyciel</h1>

<%= render 'form', teacher: @teacher %>

<center><%= link_to 'Wróć', teachers_path , :class => "btn btn-dark btn-sm"%></center>
</div>

compose/app/views/teachers/show.html.erb
<p id="notice"><%= notice %></p>
<div class="container">
	    <div class="d-inline-block">
        <h4>Dane nauczyciela : <%= @teacher.imie %> <%= @teacher.nazwisko %></h4>
    </div>
    <hr />
<p>
  <strong>Imie:</strong>
  <%= @teacher.imie %>
</p>

<p>
  <strong >Nazwisko:</strong>
  <%= @teacher.nazwisko %>
</p>

<p>
  <strong>Pesel:</strong>
  <%= @teacher.pesel %>
</p>

<p>
  <strong>Przedmiot:</strong>
  <%= @teacher.subject.nazwa %>
</p>
<center>
  <%= link_to 'Edytuj', edit_teacher_path(@teacher) , :class => "btn btn-warning btn-sm"%> |
  <%= link_to 'Wróć', teachers_path , :class => "btn btn-warning btn-sm"%>
</center>