compose/config/routes.rb
Rails.application.routes.draw do
  resources :teachers
  resources :subjects
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :students
	resources :students
	#root 'students#index'
	root 'pages#info'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

compose/app/models/subject.rb
class Subject < ApplicationRecord
		def self.search(search)
  where("nazwa LIKE ? OR opis LIKE ? ", "%#{search}%", "%#{search}%") 
end
    validates :nazwa, :length => { :in => 3..15, :message => "Długość minimum 3." }, :format => { :with => /\A[a-ząćęłńóśźż]+\z/, :message => "nie może zawierać liczb. Musi zaczynać się wielką literą." }
    validates :opis, :length => { :in => 3..50, :message => "musi mieć długość minimum 3." }
end

compose/app/controllers/subjects_controller.rb
class SubjectsController < ApplicationController
  before_action :set_subject, only: [:show, :edit, :update, :destroy]
  # GET /subjects
  # GET /subjects.json

def index
  @subjects = Subject.all
  if params[:search]
    @subjects = Subject.search(params[:search]).order("created_at DESC")
  else
    @subjects = Subject.all.order("created_at DESC")
  end
end
  # GET /subjects/1
  # GET /subjects/1.json
  def show
  end

  # GET /subjects/new
  def new
    @subject = Subject.new
  end

  # GET /subjects/1/edit
  def edit
  end

  # POST /subjects
  # POST /subjects.json
  def create
    @subject = Subject.new(subject_params)

    respond_to do |format|
      if @subject.save
        format.html { redirect_to @subject, notice: 'Pomyślnie dodano przedmiot.' }
        format.json { render :show, status: :created, location: @subject }
      else
        format.html { render :new }
        format.json { render json: @subject.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /subjects/1
  # PATCH/PUT /subjects/1.json
  def update
    respond_to do |format|
      if @subject.update(subject_params)
        format.html { redirect_to @subject, notice: 'Pomyślnie zaktualizowano przedmiot.' }
        format.json { render :show, status: :ok, location: @subject }
      else
        format.html { render :edit }
        format.json { render json: @subject.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /subjects/1
  # DELETE /subjects/1.json
  def destroy
    @subject.destroy
    respond_to do |format|
      format.html { redirect_to subjects_url, notice: 'Pomyślnie usunięto przedmiot.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_subject
      @subject = Subject.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def subject_params
      params.require(:subject).permit(:nazwa, :opis)
    end

end

compose/app/helpers/subjects_helper.rb
module SubjectsHelper
end

compose/app/views/subjects/_form.html.erb
<%= form_with(model: subject, local: true) do |form| %>
  <% if subject.errors.any? %>
    <div id="error_explanation">
      <h5 style="color:red;"><%= "Błąd." %> Nie udało się zapisać tego przedmiotu:</h5>

      <ul>
      <% subject.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<div class="container">
  <div class="btn-group form-inline">
    <%= form.label :nazwa , :class => "btn btn-warning btn-sm"%>
    <%= form.text_field :nazwa %>
  </div>

  <div class="btn-group form-inline">
    <%= form.label :opis , :class => "btn btn-warning btn-sm"%>
    <%= form.text_field :opis %>
  </div>


<p>
  <div class="actions form-inline">
    <%= form.submit 'Zapisz', :class => "btn btn-dark btn-sm"%>
  </div>
</p>

</div>
<% end %>

compose/app/views/subjects/edit.html.erb
<div class="container">
<br>
<h2><p>Edycja przedmiotów</p></h2>
<hr />
<%= render 'form', subject: @subject %>
</br>

<center>
	<%= link_to 'Wyświetl', @subject , :class => "btn btn-dark btn-sm"%> |
	<%= link_to 'Wróć', subjects_path , :class => "btn btn-dark btn-sm"%>
</center>
</div>

compose/app/views/subjects/index.html.erb
<p id="notice"><%= notice %></p>
<center><h1>Lista przedmiotów</h1></center>
<div class="container">


<%= form_tag(subjects_path, method: :get , id: "search-form") do %>
    <%= text_field_tag :search, params[:search], placeholder: "Znajdź przedmiot" %>
    <%= submit_tag "Szukaj", name: nil, class: "btn btn-warning btn-sm" %>
<% end %>

<% if @subjects.blank? %>
  <h4>Nie istnieje uczeń '<%= params[:search] %>'.</h4>
<% end %>


<center><%= link_to 'Dodaj nowy przedmiot', new_subject_path, :class => "btn btn-warning btn-sm" %></center>
</br>
<table class="table table-stripped table-hover">

  <thead>
    <tr>
      <th>Nazwa</th>
      <th>Opis</th>
      <th colspan="2"></th>
    </tr>
  </thead>

  <tbody>
    <% @subjects.each do |subject| %>
      <tr>
        <td><%= subject.nazwa %></td>
        <td><%= subject.opis %></td>
        <td><%= link_to 'Wyświetl', subject, :class => "btn btn-dark btn-sm" %></td>
        <td><%= link_to 'Edytuj', edit_subject_path(subject) , :class => "btn btn-warning btn-sm" %></td>
        
       <td><%= link_to 'Usuń', subject, method: :delete, data: { confirm: 'Czy na pewno chcesz usunąć?' }, :class => "btn btn-dark btn-sm"  %></td>
      <!--   <td><%= link_to 'Usuń', subjects_path , :class => "btn btn-dark btn-sm"%></td>-->
    <% end %>
  </tbody>
</table>
     <%= link_to 'Anuluj szukanie', subjects_path , :class => "btn btn-dark btn-sm"%>

</div>
<br>

compose/app/views/subjects/new.html.erb
<div class="container">
<h1>Nowy przedmiot</h1>

<%= render 'form', subject: @subject %>

<center><%= link_to 'Wróć', subjects_path , :class => "btn btn-dark btn-sm"%></center>
</div>

compose/app/views/subjects/show.html.erb
<p id="notice"><%= notice %></p>
<div class="container">
	    <div class="d-inline-block">
        <h4>Przedmiot : <%= @subject.nazwa %></h4>
    </div>
    <hr />
<p>
  <strong>Nazwa:</strong>
  <%= @subject.nazwa %>
</p>

<p>
  <strong >Opis:</strong>
  <%= @subject.opis %>
</p>

<center>
  <%= link_to 'Edytuj', edit_subject_path(@subject) , :class => "btn btn-warning btn-sm"%> |
  <%= link_to 'Wróć', subjects_path , :class => "btn btn-warning btn-sm"%>
</center>